spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev #开发环境
  application:
    name: micoservicecloud-config-dev
server:
  port: 8201

---
spring:
  profiles: test #开发环境
  application:
    name: micoservicecloud-config-test
server:
  port: 8202
#请保存为UTF-8格式